tradutor_rails/config/routes.rb
Rails.application.routes.draw do

  root to:'translations#index'
  resources :translations
  resources :translation_requests, only: [:new, :create, :show]



  #get 'translations', to: 'translations#list'
  #get 'translation/:id', to: 'translations#show', as: 'translation'
  #get 'new_translation', to: 'translations#new'
  #post 'translations', to: 'translations#create'
  #get 'translation/:id/edit', to:'translations#edit', as: 'edit_translation'
  #patch 'translation/:id', to:'translations#update'
  #put 'translation/:id', to:'translations#update'
  #delete 'translation/:id', to: 'translations#destroy'
  #resources :translations
end

tradutor_rails/app/models/concerns/aplication_record.rb
class AplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end 

tradutor_rails/app/models/translation.rb
class Translation < ActiveRecord::Base
end

tradutor_rails/app/models/translation_request.rb
class TranslationRequest < ActiveRecord::Base
end

tradutor_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

tradutor_rails/app/controllers/traducoes_controller.rb
#Adiciona a classe Traducoes.controller para a aplicação.
#Herda a classe ApplicationController, ou seja, a classe que eu criei torna-se uma extensão da classe ApplicationController, que o rails considera como padrão

class TraducoesController < ApplicationController
  #Define o método lista e define todas as traducoes encontradas em lista
 def lista
   @traducoes = Traducoes.all
 end
end

tradutor_rails/app/controllers/translation_requests_controller.rb
class TranslationRequestsController <ApplicationController

  def new
    @translation_request = TranslationRequest.new
  end

  def create
    @translation_request = TranslationRequest.new(translation_request_params)
    @translation_request.save

    redirect_to @translation_request
  end

  def show
    @translation_request = TranslationRequest.find(params[:id])
  end

end


private
def translation_request_params
  params.require(:translation_request).permit(:text)
end

tradutor_rails/app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :find_translation, only: [:show, :edit, :update, :destroy]
  

  def index
     @translations = Translation.all
  end

   def new
    @translation = Translation.new
  end

  def create

    @translation = Translation.new(translation_params)

    @translation.save
    redirect_to @translation
  end

  def edit
  end

  def show
  end

  def update

    if @translation.update(translation_params)
      redirect_to @translation
    else
      render 'edit'
    end
  end

  def destroy
     @translation.destroy

     redirect_to translations_path
   end

  private
    def translation_params
      params.require(:translation).permit(:portuguese, :english)
    end

    def find_translation
      @translation = Translation.find(params[:id])
    end
end

tradutor_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

tradutor_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TradutorRuby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

tradutor_rails/app/views/traducoes/lista.html.erb
<!--Adiciona template para a classe Traducoes/-->

<h1>Lista de Traduções </h1>

<!--loop para achar cada tradução dentro da lista de traduções e print com a traducao em portgues e ingles./-->
<ul>
<% @traducoes.each do |traducao| %>
  <li>Tradução de <%= traducao.portuguese %> é <%= traducao.english %>
<% end %>
</ul>

tradutor_rails/app/views/translation_requests/new.html.erb
<%= form_for @translation_request do |f| %>

  <p>
    <%= f.label :text, 'Texto' %><br>
    <%= f.text_field :text %>
  </p>

<%= f.submit 'Enviar' %>

<% end %>

tradutor_rails/app/views/translation_requests/show.html.erb
<h1>Solicitação de tradução efetuada</h1>

<%= link_to 'Voltar', root_path %>

tradutor_rails/app/views/translations/edit.html.erb
<%= form_for @translation do |f| %>

  <p>
    <%= f.label :portuguese %><br>
    <%= f.text_field :portuguese %>
  </p>

  <p>
    <%= f.label :english %><br>
    <%= f.text_field :english %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

tradutor_rails/app/views/translations/index.html.erb
<!--Adiciona template para a classe Traducoes/-->

<h1>Lista de Termos traduzidos </h1>

<%= link_to 'Solicitar tradução', new_translation_request_path %>
<%= link_to 'Enviar uma tradução', new_translation_path %>

<!--loop para achar cada tradução dentro da lista de traduções e print com a traducao em portgues e ingles./-->
<% if @translations.empty? %>
  <p> Nao existem traducoes ainda</p>
  <% end %>

<ul>
<% @translations.each do |t| %>
  <li><a href ="/translations/<%= t.id %>"><%= t.portuguese %></a></li>
<% end %>
</ul>

tradutor_rails/app/views/translations/list.html.erb
<!--Adiciona template para a classe Traducoes/-->

<h1>Lista de Termos traduzidos </h1>

<!--loop para achar cada tradução dentro da lista de traduções e print com a traducao em portgues e ingles./-->
<ul>
<% @translations.each do |t| %>
  <li><a href ="/translation/<%= t.id %>"><%= t.portuguese %></a></li>
<% end %>
</ul>


<%= link_to 'Nova tradução', new_translation_path %>

tradutor_rails/app/views/translations/new.html.erb
<%= form_for :translation, url: translations_path do |f| %>

  <p>
    <%= f.label :english, 'Ingles' %><br>
    <%= f.text_field :english %>
  </p>

  <p>
    <%= f.label :portuguese, 'Portugues' %><br>
    <%= f.text_field :portuguese %>
  </p>

  <p>
    <%= f.submit 'Enviar'%>
  </p>
<% end %>

tradutor_rails/app/views/translations/show.html.erb
<h1>Tradução de <%= @translation.portuguese %></h1>

<p>A tradução é: <%= @translation.english %>


<%= link_to 'Editar', edit_translation_path(@translation) %>

<%= link_to 'Voltar', root_path %>

<%= link_to 'Apagar', translation_path(@translation),
            method: :delete,
            data: { confirm: 'Tem certeza que deseja deletar?' } %>